spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/publicacoes
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true


